"use client";

import Head from "next/head";
import {
  AiOutlineWhatsApp,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import self from "../public/selfPic.png";
import ticket from "../public/images/ticket.png";
import exam from "../public/images/exam.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-10 lg:px-20">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between text-black dark:text-white">
            <h1 className="font-caveat text-5xl text-teal-800 dark:text-teal-200">Ayan&apos;s Portfolio</h1>
            <ul className="flex items-center">
              <li className="shadow rounded p-2">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li className="font-serif">
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="/resume/AyanNandiResume.pdf" target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 mb-4 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Ayan Nandi
            </h2>
            <h3 className="font-grandHotel text-2xl py-2 text-teal-800 dark:text-white md:text-4xl">
              A Software Enthusiast and Computer Science Explorer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              A Master&apos;s student, pursuing research in Computer Science, as well as
              cultivating skills to develop software and apps and contribute to the ever-evolving community.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://wa.link/no8uel" target="_blank"><AiOutlineWhatsApp /></a>
              <a href="https://www.linkedin.com/in/ayan-nandi-683b69187" target="_blank"><AiFillLinkedin /></a>
              <a href="https://github.com/ayanNandi410" target="_blank"><AiFillGithub /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={self} />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 mt-5 mb-3 text-black dark:text-white ">What I do</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I love to build web apps, learning different frameworks and understanding the Web. I have also worked 
              to develop Android Apps and learnt several languages as well. I am looking for 
              <span className="text-teal-600"> Software Development Roles </span>
              and willing to learn and work as and when needed. 
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including
              programming, software testing and teaching.
            </p>
          </div>
          <h3 className="text-3xl mt-5 py-1 text-black dark:text-white ">Projects I have worked on</h3>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-6 rounded-xl my-10 text-black hover:bg-sky-100 dark:bg-black text-white flex-1 dark:hover:bg-slate-800">
              <Image src={ticket} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                BookShow 2.0
              </h3>
              <p className="text-black dark:text-white mt-4">A Ticket Booking System with Admin Section</p>
              <p className="text-blue-700 dark:text-blue-400 mt-4">VueJS | Flask | Bootstrap | Celery</p>
            </div>

            <div className="text-center shadow-lg p-6 rounded-xl my-10 text-black hover:bg-sky-100 dark:bg-black text-white flex-1 dark:hover:bg-slate-800">
              <Image src={ticket} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                BookShow 1.0
              </h3>
              <p className="text-black dark:text-white mt-4">A Ticket Booking System with Admin Section</p>
              <p className="text-blue-700 dark:text-blue-400 mt-4"> Flask | HTML | Bootstrap</p>
            </div>

            <div className="text-center shadow-lg p-6 rounded-xl my-10 text-black hover:bg-sky-100 dark:bg-black text-white flex-1 dark:hover:bg-slate-800">
              <Image src={exam} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                ExamApp
              </h3>
              <p className="text-black dark:text-white mt-4">An Examination System for Students and Teachers</p>
              <p className="text-blue-700 dark:text-blue-400 mt-4"> Android(Java) | ExpressJS </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 mb-6 text-black dark:text-white ">Languages Learnt</h3>
              <button className="bg-transparent me-4 hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                Python
              </button>
              <button className="bg-transparent me-4 hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                Java
              </button>
              <button className="bg-transparent me-4 hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                C/C++
              </button>
              <button className="bg-transparent me-4 hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                HTML
              </button>
              <button className="bg-transparent me-4 hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                CSS
              </button>
              <button className="bg-transparent me-4 hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                Javascript
              </button>
              <button className="bg-transparent me-4 hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                SQL
              </button>
          </div>
        </section>
      </main>
      <footer className="text-center p-3 bg-slate-100 w-full text-black dark:bg-black dark:text-white"> &copy; 2023  |  Made by Ayan Nandi</footer>
    </div>
  );
}